export const STORAGE_CREDENTIALS = 'STORAGE_CREDENTIALS';
export const STORAGE_USERNAME = 'STORAGE_USERNAME';
export const STORAGE_USER_ROLES = 'STORAGE_USER_ROLES';
export const STORAGE_COUNTED_BY = 'STORAGE_FIRST_COUNTED_BY';

export const STORAGE_COLLECTOR_IDENTIFIER = 'STORAGE_COLLECTOR_IDENTIFIER';
export const STORAGE_BOX_IDENTIFIER = 'STORAGE_BOX_IDENTIFIER';
export const STORAGE_COLLECTOR_NAME = 'STORAGE_COLLECTOR_NAME';
export const STORAGE_IS_BOX_SPECIAL = 'STORAGE_IS_BOX_SPECIAL';

// CustomTable visible columns
export const STORAGE_VISIBLE_COLUMNS = 'STORAGE_VISIBLE_COLUMNS';
