export const STORAGE_CREDENTIALS = 'STORAGE_CREDENTIALS';
export const STORAGE_USERNAME = 'STORAGE_USERNAME';

export const STORAGE_COLLECTOR_IDENTIFIER = 'STORAGE_COLLECTOR_IDENTIFIER';
export const STORAGE_BOX_IDENTIFIER = 'STORAGE_BOX_IDENTIFIER';
export const STORAGE_COLLECTOR_NAME = 'STORAGE_COLLECTOR_NAME';
